"""Deterministic, data-only CadQuery source artifact generation."""

from __future__ import annotations

import ast
from collections.abc import Mapping
from pathlib import Path

from mesh2param_contracts import CADGraph, canonical_json

_ALLOWED_IMPORT_ROOTS = {"cadquery", "mesh2param", "mesh2param_contracts"}
_BANNED_CALLS = {"eval", "exec", "compile", "__import__", "open", "input"}


def _validate_generated_source(source: str) -> None:
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            roots = {alias.name.split(".", 1)[0] for alias in node.names}
            if not roots <= _ALLOWED_IMPORT_ROOTS:
                raise ValueError(f"generated source contains disallowed import: {sorted(roots)}")
        elif isinstance(node, ast.ImportFrom):
            root = (node.module or "").split(".", 1)[0]
            if root not in _ALLOWED_IMPORT_ROOTS:
                raise ValueError(f"generated source contains disallowed import: {root}")
        elif isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            if node.func.id in _BANNED_CALLS:
                raise ValueError(f"generated source contains disallowed call: {node.func.id}")


def generate_cadquery_source(
    graph: CADGraph,
    *,
    artifact_paths: Mapping[str, str | Path] | None = None,
) -> str:
    """Generate source from validated AST data without interpolating Python code.

    The application never executes this artifact.  It is intentionally a thin,
    auditable replay file that invokes the same trusted compiler as the API and
    CLI, preventing source and authoritative CADGraph behavior from diverging.
    """

    document = canonical_json(graph)
    paths = {
        key: str(value)
        for key, value in sorted((artifact_paths or {}).items(), key=lambda item: item[0])
    }
    feature_comments = "\n".join(
        f"# feature {feature.order}: {feature.id} ({feature.operation})"
        for feature in graph.features
    )
    source = (
        '"""Generated by Mesh2Param from a validated CADGraph.\n\n'
        "Units: "
        + graph.units
        + ". This file is an export artifact, not authoritative project state.\n"
        '"""\n\n'
        "import cadquery as cq\n"
        "from mesh2param import compile_cadgraph\n"
        "from mesh2param_contracts import CADGraph\n\n"
        + feature_comments
        + "\n\n"
        + f"CADGRAPH_JSON = {document!r}\n"
        + f"ARTIFACT_PATHS = {paths!r}\n\n"
        + "graph = CADGraph.model_validate_json(CADGRAPH_JSON)\n"
        + "result = compile_cadgraph(graph, artifact_resolver=ARTIFACT_PATHS)\n"
        + "model: cq.Shape = result.require_shape()\n"
    )
    _validate_generated_source(source)
    return source


def write_cadquery_source(
    graph: CADGraph,
    path: str | Path,
    *,
    artifact_paths: Mapping[str, str | Path] | None = None,
) -> Path:
    destination = Path(path)
    if destination.suffix.lower() != ".py":
        raise ValueError("CadQuery source output must use a .py extension")
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        generate_cadquery_source(graph, artifact_paths=artifact_paths),
        encoding="utf-8",
        newline="\n",
    )
    return destination


__all__ = ["generate_cadquery_source", "write_cadquery_source"]
