"""Named geometry tolerances with explicit units and domains.

These constants centralize existing defaults; they do not establish one global
epsilon.  Geometry algorithms should continue to choose the tolerance that
matches their coordinate system and physical meaning.
"""

DEFAULT_TESSELLATION_LINEAR_TOLERANCE_MM = 0.1
DEFAULT_TESSELLATION_ANGULAR_TOLERANCE_RAD = 0.1
DEFAULT_TESSELLATION_COORDINATE_RESOLUTION_MM = 1e-6
MINIMUM_OCCT_TESSELLATION_TOLERANCE = 1e-6
TESSELLATION_VALIDATION_LINEAR_TOLERANCE_MM = 1e-3
DEGENERATE_NORMAL_MAGNITUDE_EPSILON = 1e-30

DEFAULT_COMPARISON_LINEAR_TESSELLATION_MM = 0.025
DEFAULT_COMPARISON_ANGULAR_TESSELLATION_RAD = 0.1

CURVED_RESULT_LINEAR_TESSELLATION_MM = 0.002
CURVED_RESULT_ANGULAR_TESSELLATION_RAD = 0.2


__all__ = [
    "CURVED_RESULT_ANGULAR_TESSELLATION_RAD",
    "CURVED_RESULT_LINEAR_TESSELLATION_MM",
    "DEFAULT_COMPARISON_ANGULAR_TESSELLATION_RAD",
    "DEFAULT_COMPARISON_LINEAR_TESSELLATION_MM",
    "DEFAULT_TESSELLATION_ANGULAR_TOLERANCE_RAD",
    "DEFAULT_TESSELLATION_COORDINATE_RESOLUTION_MM",
    "DEFAULT_TESSELLATION_LINEAR_TOLERANCE_MM",
    "DEGENERATE_NORMAL_MAGNITUDE_EPSILON",
    "MINIMUM_OCCT_TESSELLATION_TOLERANCE",
    "TESSELLATION_VALIDATION_LINEAR_TOLERANCE_MM",
]
