# ruff: noqa
"""Establish the initial Mesh2Param database schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-20 00:14:21.232153
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_blobs',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.String(length=160), nullable=False),
    sa.Column('storage_key', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sha256'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('units', sa.String(length=4), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("units IN ('mm','cm','m','in','ft')", name='ck_project_units'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('input_version_id', sa.String(length=36), nullable=True),
    sa.Column('output_version_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mutates_project', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('input_revision', sa.BigInteger(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('settings_hash', sa.String(length=64), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('deterministic_seed', sa.BigInteger(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('phase', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timeout_seconds', sa.Float(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('current_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_summary', sa.String(length=400), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('error_recoverable', sa.Boolean(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','completed','cancelled','failed')", name='ck_job_status'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='ck_job_progress'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_cache_key'), 'jobs', ['cache_key'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('uq_jobs_one_active_mutation', 'jobs', ['project_id'], unique=True, sqlite_where=sa.text("mutates_project IS 1 AND status IN ('queued', 'running')"), postgresql_where=sa.text("mutates_project IS 1 AND status IN ('queued', 'running')"))
    op.create_table('project_states',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.BigInteger(), nullable=False),
    sa.Column('document_json', sa.JSON(), nullable=False),
    sa.Column('based_on_version_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('source_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('encoding', sa.String(length=40), nullable=False),
    sa.Column('blob_sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('declared_units', sa.String(length=4), nullable=False),
    sa.Column('units_confirmed', sa.Boolean(), nullable=False),
    sa.Column('scale_factor', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('diagnostics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("format IN ('stl','obj','ply','generated')", name='ck_source_format'),
    sa.CheckConstraint("state IN ('pending','valid','invalid')", name='ck_source_state'),
    sa.ForeignKeyConstraint(['blob_sha256'], ['artifact_blobs.sha256'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_assets_project_id'), 'source_assets', ['project_id'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('state_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('repair_hash', sa.String(length=64), nullable=True),
    sa.Column('segmentation_hash', sa.String(length=64), nullable=True),
    sa.Column('validation_status', sa.String(length=40), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('artifact_set_id', sa.String(length=36), nullable=True),
    sa.Column('engine_version', sa.String(length=80), nullable=False),
    sa.Column('dependency_versions_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_project_id'), 'versions', ['project_id'], unique=False)
    op.create_table('artifact_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('validation_state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("validation_state IN ('pending','valid','valid-with-warnings','invalid')", name='ck_artifact_set_validation'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_sets_project_id'), 'artifact_sets', ['project_id'], unique=False)
    op.create_table('audit_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_request_id'), 'audit_records', ['request_id'], unique=False)
    op.create_table('job_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('run_token', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('worker_pid', sa.Integer(), nullable=True),
    sa.Column('workdir_token', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.CheckConstraint("status IN ('running','completed','cancelled','failed')", name='ck_attempt_status'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_attempts_job_id'), 'job_attempts', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_attempts_run_token'), 'job_attempts', ['run_token'], unique=True)
    op.create_index('uq_job_attempt_number', 'job_attempts', ['job_id', 'attempt_number'], unique=True)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_set_id', sa.String(length=36), nullable=False),
    sa.Column('logical_name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('blob_sha256', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=160), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_set_id'], ['artifact_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blob_sha256'], ['artifact_blobs.sha256'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_artifact_set_id'), 'artifacts', ['artifact_set_id'], unique=False)
    op.create_index('uq_artifact_set_name', 'artifacts', ['artifact_set_id', 'logical_name'], unique=True)
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=80), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('progress IS NULL OR (progress >= 0 AND progress <= 100)', name='ck_event_progress'),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('operation_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('artifact_set_id', sa.String(length=36), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('engine_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_set_id'], ['artifact_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cache_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_cache')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('uq_artifact_set_name', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_set_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('uq_job_attempt_number', table_name='job_attempts')
    op.drop_index(op.f('ix_job_attempts_run_token'), table_name='job_attempts')
    op.drop_index(op.f('ix_job_attempts_job_id'), table_name='job_attempts')
    op.drop_table('job_attempts')
    op.drop_index(op.f('ix_audit_records_request_id'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_artifact_sets_project_id'), table_name='artifact_sets')
    op.drop_table('artifact_sets')
    op.drop_index(op.f('ix_versions_project_id'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_source_assets_project_id'), table_name='source_assets')
    op.drop_table('source_assets')
    op.drop_table('project_states')
    op.drop_index('uq_jobs_one_active_mutation', table_name='jobs', sqlite_where=sa.text("mutates_project IS 1 AND status IN ('queued', 'running')"), postgresql_where=sa.text("mutates_project IS 1 AND status IN ('queued', 'running')"))
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_cache_key'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('projects')
    op.drop_table('artifact_blobs')
    # ### end Alembic commands ###
