import { useRef, useState, type CSSProperties, type KeyboardEvent, type PointerEvent } from "react";
import { Copy, Trash2 } from "lucide-react";
import { Button, Tabs } from "@mesh2param/ui";
import type { JobLogEntry } from "../state/types";

type Tab="tips"|"logs"|"metrics";
export function BottomDrawer({logs,metrics,height,onHeight}:{logs:JobLogEntry[];metrics:Record<string,unknown>|null;height:number;onHeight(value:number):void}){const [tab,setTab]=useState<Tab|null>(null);const drag=useRef<{y:number;height:number}|null>(null);function down(e:PointerEvent<HTMLButtonElement>){drag.current={y:e.clientY,height};e.currentTarget.setPointerCapture(e.pointerId)}function move(e:PointerEvent<HTMLButtonElement>){if(!drag.current)return;onHeight(Math.max(160,Math.min(innerHeight-140,drag.current.height+drag.current.y-e.clientY)))}function up(e:PointerEvent<HTMLButtonElement>){drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}function key(e:KeyboardEvent<HTMLButtonElement>){let next:number|null=null;if(e.key==="ArrowUp")next=height+24;if(e.key==="ArrowDown")next=height-24;if(e.key==="Home")next=160;if(e.key==="End")next=innerHeight-140;if(next!==null){e.preventDefault();onHeight(Math.max(160,Math.min(innerHeight-140,next)))}}
 const items=[{id:"tips" as const,label:"Tips"},{id:"logs" as const,label:"Logs",count:logs.length},{id:"metrics" as const,label:"Metrics",count:metrics?Object.keys(metrics).length:0}];return <section className={`bottom-drawer ${tab?"expanded":""}`} style={tab?{"--drawer-height":`${height}px`} as CSSProperties:undefined} aria-label="Workspace information"><div className="drawer-tabs"><Tabs label="Workspace information" items={items} value={tab} onChange={next=>setTab(tab===next?null:next)}/></div>{tab?<div className="drawer-content"><button className="drawer-resize" role="separator" aria-orientation="horizontal" aria-valuemin={160} aria-valuemax={innerHeight-140} aria-valuenow={height} aria-label="Resize bottom drawer" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onKeyDown={key}/>{tab==="tips"?<Tips/>:tab==="logs"?<Logs logs={logs}/>:<Metrics metrics={metrics}/>}</div>:null}</section>}
function Tips(){return <div className="tips-grid"><article><strong>Orbit and inspect</strong><p>Drag to orbit, right-drag to pan, and press H to fit the model.</p></article><article><strong>Evidence first</strong><p>Select a patch or feature to review its fit, evidence, residuals, and confidence.</p></article><article><strong>Last valid geometry</strong><p>An invalid edit never replaces the latest kernel-valid B-Rep.</p></article><article><strong>Keyboard</strong><p>N/B step · A analyze · R reconstruct · E export · 1–7 steps.</p></article></div>}
function Logs({logs}:{logs:JobLogEntry[]}){const text=logs.map(log=>`${new Date(log.timestamp).toLocaleTimeString([],{hour12:false})} ${log.level.toUpperCase()} ${log.phase} ${log.message}`).join("\n");return <div className="logs-panel"><div><strong>Job logs</strong><span><Button onClick={()=>void navigator.clipboard?.writeText(text)}><Copy/>Copy</Button><Button disabled><Trash2/>Clear</Button></span></div><pre>{text||"No job logs yet."}</pre></div>}
function Metrics({metrics}:{metrics:Record<string,unknown>|null}){return <div className="metrics-panel"><div className="metric-header"><span>Metric</span><span>Value</span></div>{metrics?Object.entries(metrics).map(([key,value])=><div key={key}><span>{key}</span><strong>{typeof value==="number"?value.toPrecision(6):String(value)}</strong></div>):<p>No comparison metrics yet.</p>}</div>}
